//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDN_FX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdateCommunityXML {
            get {
                return ((bool)(this["AutoUpdateCommunityXML"]));
            }
            set {
                this["AutoUpdateCommunityXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadNonUniqueTitles {
            get {
                return ((bool)(this["DownloadNonUniqueTitles"]));
            }
            set {
                this["DownloadNonUniqueTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadSystemTitles {
            get {
                return ((bool)(this["DownloadSystemTitles"]));
            }
            set {
                this["DownloadSystemTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCIAStringFormat {
            get {
                return ((bool)(this["UseCIAStringFormat"]));
            }
            set {
                this["UseCIAStringFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseIndividualFolders {
            get {
                return ((bool)(this["UseIndividualFolders"]));
            }
            set {
                this["UseIndividualFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTMTicketDBPath {
            get {
                return ((string)(this["DefaultTMTicketDBPath"]));
            }
            set {
                this["DefaultTMTicketDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTMOutputPath {
            get {
                return ((string)(this["DefaultTMOutputPath"]));
            }
            set {
                this["DefaultTMOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTDLEncTitleKeyPath {
            get {
                return ((string)(this["DefaultTDLEncTitleKeyPath"]));
            }
            set {
                this["DefaultTDLEncTitleKeyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTDLOutputPath {
            get {
                return ((string)(this["DefaultTDLOutputPath"]));
            }
            set {
                this["DefaultTDLOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTDLTikOutputPath {
            get {
                return ((string)(this["DefaultTDLTikOutputPath"]));
            }
            set {
                this["DefaultTDLTikOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultNUSOutputPath {
            get {
                return ((string)(this["DefaultNUSOutputPath"]));
            }
            set {
                this["DefaultNUSOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CommunityXMLVersion {
            get {
                return ((string)(this["CommunityXMLVersion"]));
            }
            set {
                this["CommunityXMLVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdate3DSDBXML {
            get {
                return ((bool)(this["AutoUpdate3DSDBXML"]));
            }
            set {
                this["AutoUpdate3DSDBXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdateTitlelistCSV {
            get {
                return ((bool)(this["AutoUpdateTitlelistCSV"]));
            }
            set {
                this["AutoUpdateTitlelistCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentTMTicketDBPath {
            get {
                return ((string)(this["CurrentTMTicketDBPath"]));
            }
            set {
                this["CurrentTMTicketDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentTMOutputPath {
            get {
                return ((string)(this["CurrentTMOutputPath"]));
            }
            set {
                this["CurrentTMOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentTDLEncTitleKeyPath {
            get {
                return ((string)(this["CurrentTDLEncTitleKeyPath"]));
            }
            set {
                this["CurrentTDLEncTitleKeyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentTDLOutputPath {
            get {
                return ((string)(this["CurrentTDLOutputPath"]));
            }
            set {
                this["CurrentTDLOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentTDLTikOutputPath {
            get {
                return ((string)(this["CurrentTDLTikOutputPath"]));
            }
            set {
                this["CurrentTDLTikOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentNUSOutputPath {
            get {
                return ((string)(this["CurrentNUSOutputPath"]));
            }
            set {
                this["CurrentNUSOutputPath"] = value;
            }
        }
    }
}
